### ISSUE TITLE
Incoming donations

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#25]
## general

This issue is an comparison of the user flow and what has to happen in parallel in odoo. I created this issue to give an structured overview of what needs to be done and why.

## user flow
@jamescrowley created a nice *user flow how new stock should be registered in Boxwise*.
![52898091-0ea77d80-31da-11e9-9b01-b974af9e7ace](https://user-images.githubusercontent.com/29065125/52948433-b4ddb980-3379-11e9-929b-cbfcee9aa16b.png)

#### ToDos:

- [x] #13 

## odoo dev tasks
Here, each subsection describes steps in the user flow diagram above and what the connected odoo dev tasks are (ordered according to the user flow).

#### Generate QR-codes and print them

- [x] #9 Create empty packages / boxes in odoo
- [x] #24 Assign a unique identifier to each package / box.
- [x] (optional #27) Store the right data in the QR-code.
- [ ] (optional #26) Store created qr-code as a field in `stock.quant.package`
- [x] #23 Create a pdf layout to print the QR-code.
- [ ] (optional #32) Download created packages automatically.

#### Register the contents of a box

- [x] #14 Create a supplier in odoo from where new stock is coming from. 
- [ ] #4 Create a mobile form which is dynamic depending on products and variants.
- [ ] #5 Create a odoo receipt to register incoming donations.
- [ ] #6 Design the infoscreen which is shown when a box is scanned again.
