### ISSUE TITLE
Add a QR odoo field for packages to save the related QR-codes.

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#26]
## Context
Each package needs to have a QR-code. Since we might want to change in the future what data is saved in QR-codes or want to reprint QR-codes of Boxes, we should save the QR-code for each box.

## ToDos
- [ ] Add a qr-code field to stock.quant.package where you can store the qr-code. This field does not need to save an image, but can also just save the information which is stored in the QR-code.
- [ ] Add an action when a box is created that it automatically saves the QR-code information to the corresponding field.
- [ ] Show the qr-code of each package in corresponding form.
![image](https://user-images.githubusercontent.com/29065125/52209617-c35da880-2884-11e9-80f8-43e591ed639a.png)

**Comment by jamescrowley** [comment]
@HaGuesto I'm closing this as we know how we're generating the QR codes in v1:

http://app.boxwise.co/qrcode/pampiraiki/{name}-{dbid} 

And can always therefore recreate them even if we subsequently change the format.
