### ISSUE TITLE
Fix importing product variants

### ISSUE THREAD

**Issue by jamescrowley** [boxwise/boxwise_wms#82]
## Context

In the pampiraiki data we still have issues with importing data repeatedly - it tries to delete and re-create which doesn't work the moment you have packages containing those products. It already does not work if you want to update product.templates .

## Idea
We think this is because we are not specifying attribute_line_ids/id in the import file. If we add this column then hopefully the problems with magically disappear.

## ToDo
- [ ] Add a product.attribute.line.csv. Three columns are needed:  attribute_id/id , product_tmpl_id/id, value_ids/id
- [ ] Move all attribute lines from product.template to product.attribute.line
- [ ] Specify in product.attribute.line.csv unique ids.
- [ ] In product.template add a column attribute_line_ids/id (maybe it is not needed).

**Comment by jamescrowley** [comment]
I'm not sure it's necessary to split out the files. I think it can still be specified inline by simply adding the new column?
