### ISSUE TITLE
Create empty packages in bulk through an extra menu

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#9]
### Generate QR codes

This tasks should replicate the workflow of the [Generate QR codes](https://test.drop-app.de/?action=qr) menu in Drop App.

![image](https://user-images.githubusercontent.com/29065125/51791969-75bdad80-21ab-11e9-9a94-0c0e1c9bd8a2.png)

**These steps must be implemented**

- [x] A new menu to generate QR-codes must be added.
- [x] Create a form where u define how many QR-codes should be created. [This](https://www.odoo.com/documentation/11.0/howtos/backend.html#wizards) might be needed.
- [x] When submitting the form it should create a number of empty packages at once. The submit button will most likely have to trigger a [server action](https://www.odoo.com/documentation/11.0/reference/actions.html#server-actions-ir-actions-server)
- [ ] After the form is closed it should automatically download the [qr-report pdf](https://github.com/boxwise/boxwise_wms/blob/master/views/report_qr_codes.xml) which is designed in #23 and then it should reload the package and show the Packages-menu in list form.

**Comment by HaGuesto** [comment]
@DurkoMatko For the creation of empty packages, I recommend you to read the first pages of chapter 6 (p. 134 and following) in the [odoo 11 essentials book](https://drive.google.com/open?id=1jY75tDjeFqJxgOb-JTeh35Pp9IOr4Irt).
You will need the `create` or `load` command.

**Comment by HaGuesto** [comment]
@DurkoMatko I also added one task. After the form is finished and processed it should call a download and a redirect to the packages menu.

Ask me if you have any questions.

**Comment by HaGuesto** [comment]
@DurkoMatko I think this might be a helpful example even though it is in odoo 10.
https://www.surekhatech.com/blog/generate-report-from-custom-wizard-in-odoo10
