### ISSUE TITLE
Call `box_view.xml` from `box_created.xml`

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise_wms#95]
## context 
`box_view.xml` and `box_created.xml` both show the same table about what a box contains.

## Idea
Instead of writing the same code twice, `box_created.xml` should call `box_view.xml` as a template.

## ToDo
- [ ] Create a box_view template.
- [ ] call it in box_created.xml
- [ ] the former box_view should still exist as a view , not just a template, since it populates the "/box/<box-number>" address. Therefore, keep the `box_view` view and call the template in it, too.
